### ISSUE TITLE
Create database for app

### ISSUE THREAD

**Issue by andreeafiterau** [andreeafiterau/VotingApp#1]
![IMG_20201208_161519 2](https://user-images.githubusercontent.com/58468337/101495668-a4ffe280-391d-11eb-9c6b-98f0eafc809b.jpg)
![IMG_20201208_161514 1](https://user-images.githubusercontent.com/58468337/101495739-bba63980-391d-11eb-8f01-26ce78f73208.jpg)

**Comment by DianaPredoiu** [comment]
@andreeafiterau ai timp maine de o sedinta scurta sa discutam despre db ? daca da, da mi mail cu ora. eu pot oricand inafara de 12-13 gen

**Comment by andreeafiterau** [comment]
Da am timp, se poate de la 9 jum? Ca sa ma apuc apoi de treaba:)

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 8, 2020 at 4:34 PM, DianaPredoiu<notifications@github.com> wrote:   


@andreeafiterau ai timp maine de o sedinta scurta sa discutam despre db ? daca da, da mi mail cu ora. eu pot oricand inafara de 12-13 gen

**Comment by DianaPredoiu** [comment]
da, la 9 jumate ramane :)

**Comment by andreeafiterau** [comment]
Oki, seara faina!

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 8, 2020 at 4:37 PM, DianaPredoiu<notifications@github.com> wrote:   


da, la 9 jumate ramane :)

**Comment by DianaPredoiu** [comment]
![Capture](https://user-images.githubusercontent.com/18480831/101601883-e075dc00-3a05-11eb-82c6-fabdfdeae3f3.PNG)

**Comment by DianaPredoiu** [comment]
Hello. Tabelele gri le eliminam din schema. Deocamdata pare ok ce e acum. Vezi daca vrei sa faci code first si daca folosesti entity sa se genereze tabelele pe codul scris de tine. Spor si daca mai am idei pt DB revin aici :)
![Capture](https://user-images.githubusercontent.com/18480831/101608369-4a927f00-3a0e-11eb-8fdc-0c006b411073.PNG)

**Comment by andreeafiterau** [comment]
Oki,multu:)

**Comment by andreeafiterau** [comment]
Updated the initial database with EfCore Code First Method , modified all controllers and services to work on the new database and tested all with insomnia.

**Comment by DianaPredoiu** [comment]
Alegere-User-Role-Dep
id alegere
id role
id departament
