### ISSUE TITLE
Admin functionalities

### ISSUE THREAD

**Issue by DianaPredoiu** [andreeafiterau/VotingApp#3]
I made a schema for the admin feature, so it is easier and more simple to create the back-end methods.

![IMG_20201218_164852](https://user-images.githubusercontent.com/58468337/102627888-b905ca00-40fd-11eb-8695-df823206efe4.jpg)
![IMG_20201218_164823](https://user-images.githubusercontent.com/58468337/102627893-ba36f700-40fd-11eb-961e-24cf75cf2db9.jpg)
![IMG_20201218_164905](https://user-images.githubusercontent.com/58468337/102627900-bacf8d80-40fd-11eb-82a0-f82985594164.jpg)

**Comment by DianaPredoiu** [comment]
> a

aaaaa

- [ ] k
- [ ] l

**Comment by andreeafiterau** [comment]
Here I will post a list with the methods I have to implement and as I write code I will specify in the commments below what is the logic of the method and other details.

1. Colleges
   
- [x] Get
- [x] Add
- [x] Update
- [x] Delete

2. Departments

- [x] Get
- [x] Add
- [x] Update
- [x] Delete

3. Users

- [x] Get
- [x] Add
- [x] Update
- [x] Delete

4. ElectoralRoom

- [x] Get
- [x] Add
- [x] Update
- [x] Delete

5. Candidates

- [x] Get
- [x] Add
- [x] Update
- [x] Delete

6.Elections-what users can vote for each electoral room

- [x] Get
- [x] Add
- [x] Update
- [x] Delete

7.Testing

- [x] Department testing
- [x] College testing
- [x] Users Testing
- [x] ElectoralRoom Testing
- [x] Candidates Tesitng
- [x] Elections Testing

**Comment by andreeafiterau** [comment]
`Colleges`

Created CRUD Operations on Colleges table. Used Base Repository and created a new controller class.

`Departments`

Created CRUD Operations on Colleges table. Used Base Repository and created a new controller class.

**Comment by DianaPredoiu** [comment]
* first photo : each user can be in more than one college [take this into consideration when you open the edit windows for an user]

**Comment by andreeafiterau** [comment]
`Users`

Created UsersFilter for getting a list of users filtered by role, college, department.
Made constructors to initilize easier entitities into the methods.
If the account is activated admin can modify only role, college, department.
Created a controller class.

`ElectoralRoom`

Created CRUD Operations on Colleges table. Used Base Repository and created a new controller class.

`Candidates`

Created  GetCandidates method : chooses candidates from list (posible candidates for each electoral room)
Created AddCandidateOnElectoralRoom : adds electoral room for each specific candidate
Created a Controller Class.

`Elections`

Created GetUsersForElecton : gets a list with the users that can participate in a specific electorla room
Created AddUsersForElection : adds a user in the user-election table.
Created a Controller Class.

**Comment by andreeafiterau** [comment]
`Department testing
 College testing
 Users Testing
 ElectoralRoom Testing
 Candidates Tesitng
 Elections Testing`

All method were tested and they work.

Exceptions have to be handled but this part will be organized and described in the Exception Handling Issue.
